pkg/gadgets: Fix struct used as key map for tcptracer.
Before this commit, struct tuple_t was used as key of tuplepid.
But this struct does not exist, this leads to the following error message when
cross-compiling this eBPF code to arm64:
Error: can't write /mnt/pkg/gadgets/tcptracer/tracer/core/tcptracer_bpfel_arm64.go: can't load BPF from ELF: load BTF maps: map tuplepid: can't get size of BTF key: unsized type *btf.Fwd
exit status 1
So, this commit uses struct tuple_key_t in place.

Fixes: b6c9380cde28 ("tcptracer: Add bpf program")
Signed-off-by: Francis Laniel <flaniel@linux.microsoft.com>